BlackCatERP/urls.py
from django.contrib import admin
from django.urls import path, include






urlpatterns = [
    path('', include('app.base.home_urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('base/api/', include('app.base.api.urls')),
    path('product/', include('app.base.urls.product')),

]

app/home/urls.py
# Django Library
from django.conf.urls import url
from django.urls import path
from django.utils.translation import ugettext_lazy as _

# Thirdparty Library
from apps.base.views.blog import BlogView, PostDetailView
from apps.base.views.shop import WebProductDetailView, WebProductListView

# Localfolder Library
from .views.views import IndexView, UnderConstruction, contact

app_name = 'home'

urlpatterns = [
    path('', IndexView.as_view(), name='home-index'),

    path(
        'blog/',
        BlogView.as_view(
            extend_from='home/home.html',
            url_web_post='home:post',
            header_title=_("Blog")
        ),
        name='home-blog'
    ),
    path(
        'blog/post/<int:pk>/',
        PostDetailView.as_view(
            extend_from='home/home.html',
            url_web_post='home:web-blog',
            header_title=_("Blog")
        ),
        name='post'
    ),

    path(
        'shop/',
        WebProductListView.as_view(
            extend_from='home/home.html',
            url_web_product='home:web-product',
            header_title=_("Shop")
        ),
        name='web-shop'
    ),
    path(
        'shop/product/<int:pk>/',
        WebProductDetailView.as_view(
            extend_from='home/home.html',
            url_web_shop='home:web-shop',
            header_title=_("Shop")
        ),
        name='web-product'
    ),

    url(r'^license/', license, name='home-license'),
    url(r'^under-construction/', UnderConstruction, name='under-construction'),
    url(r'^contact_me$', contact, name='contact-me'),

]

app/base/models/menu.py
# Django Library
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

# Localfolder Library
from ..models.basemodel import ERPBase


class PyMenu(ERPBase):
    name = models.CharField(_("Menu"), max_length=40)
    parent_id = models.ForeignKey('self', null=True, blank=True, default=None, on_delete=models.PROTECT)
    link = models.CharField(_("link"), max_length=100)
    sequence = models.IntegerField(null=True, blank=True)


    class Meta:
        verbose_name = _("Menu")
        verbose_name_plural = _("Menu")

app/home/models.py
# Django Library
from django.db import models

# Localfolder Library
from .submodels.post import PyPost
from .submodels.web_payment_methods import PyWebPaymentMethod
from .submodels.website_config import WebsiteConfig

app/base/views/home.py
# Django Library
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Localfolder Library
from ..models import Company
from .bi import Bi
from .wparameter import parameter


def _web_parameter():
    web_parameter = {}
    for parametro in parameter.objects.all():
        web_parameter[parametro.name] = parametro.value
    return web_parameter


#@login_required()
def erp_home(request):
    """Vista para renderizar el dasboard del erp
    """

    bi_list = Bi.objects.filter(dashboard='home', type='indicator')
    if bi_list:
        for bi in bi_list:
            if bi.model:
                from ..models import Partner
                # print(bi.model)
    value = {
        'bi': bi_list,
        'web_parameter': _web_parameter(),
        'company': Company.objects.filter(active=True)
    }
    return render(request, "home.html", value)

app/base/views/menu.py
# Django Library
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import ugettext_lazy as _

# Localfolder Library
from ..models import PyMenu
from .web_father import (
    FatherCreateView, FatherDeleteView, FatherDetailView, FatherListView,
    FatherUpdateView)

OBJECT_LIST_FIELDS = [
    {'string': _("Name"), 'field': 'name'},
    {'string': _("Parent"), 'field': 'parent_id'},
    {'string': _("Link"), 'field': 'link'},
    {'string': _("Sequence"), 'field': 'sequence'},
]

OBJECT_FORM_FIELDS = ['name', 'parent_id', 'link', 'sequence']


class MenuListView(LoginRequiredMixin, FatherListView):
    model = PyMenu
    template_name = 'base/list.html'
    extra_context = {'fields': OBJECT_LIST_FIELDS}

class MenuDetailView(LoginRequiredMixin, FatherDetailView):
    model = PyMenu
    template_name = 'base/detail.html'
    extra_context = {'fields': OBJECT_LIST_FIELDS}


class MenuCreateView(LoginRequiredMixin, FatherCreateView):
    model = PyMenu
    fields = OBJECT_FORM_FIELDS
    template_name = 'base/form.html'


class MenuUpdateView(LoginRequiredMixin, FatherUpdateView):
    model = PyMenu
    fields = OBJECT_FORM_FIELDS
    template_name = 'base/form.html'


class MenuDeleteView(LoginRequiredMixin, FatherDeleteView):
    model = PyMenu
    success_url = 'base:menus'

app/home/views/views.py
# Furture Library
from __future__ import unicode_literals

# Django Library
from django.core import serializers
from django.core.mail import EmailMessage
from django.shortcuts import HttpResponse, render
from django.template.loader import render_to_string
from django.views.generic import DetailView, ListView, TemplateView

# Thirdparty Library
from apps.base.models import PyPartner, PyProduct, PyWParameter
from apps.base.views.web_father import FatherTemplateView

# from apps.crm.submodels.lead import PyLead


def _web_parameter():
    web_parameter = {}
    for parametro in PyWParameter.objects.all():
        web_parameter[parametro.name] = parametro.value
    return web_parameter


class IndexView(FatherTemplateView):
    template_name = 'home/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['web_parameter'] = _web_parameter()
        return context



def index(request):
    web_parameter = {}
    context['web_parameter'] = _web_parameter()
    return render(request, 'home/index.html', web_parameter)

def post(request):
    context['web_parameter'] = _web_parameter()
    return render(request, 'home/post.html')

def license(request):
    context['web_parameter'] = _web_parameter()
    return render(request, 'home/license.html')

def UnderConstruction(request):
    context['web_parameter'] = _web_parameter()
    return render(request, 'home/under_construction.html')


def contact(request):
    name = request.POST.get('name')
    email = request.POST.get('email')
    phone = request.POST.get('phone')
    message = request.POST.get('message')
    partners = PyPartner.objects.filter(email=email)
    send = True
    if partners:
        partner = partners[0]
        if partner.not_email:
            send = False
    else:
        partner = PyPartner(name=name, email=email, phone=phone)
        partner.save()

    if send:
        title = name
        # lead = PyLead(name=title, content=message, partner_id=partner)
        # lead.save()
        body = render_to_string('home/contact_mail_template.html', {'name': name, 'phone': phone, 'message': message})
        email_message = EmailMessage(subject='Mensaje de usuario', body=body, from_email=email, to=['mfalcon@ynext.cl'])
        email_message.content_subtype = 'html'
        email_message.send()
        return HttpResponse(content='OK')

app/home/templates/home/contact_mail_template.html
<h1 style="font-size: 1.5em; line-height: 2em">Mensaje de usuario.</h1>
<p>Ha recibido un nuevo mensaje de contacto:</p>
<dl>
    <dt>Nombre:</dt>
    <dd>{{ name }}</dd>
    <dt>Teléfono:</dt>
    <dd>{{ phone }}</dd>
    <dt>Mensaje:</dt>
    <dd>{{ message }}</dd>
</dl>

app/home/templates/home/footer.html
{% load erp_tags %}
<!-- Clients -->
  <section class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-6">
          <a href="#">
            <img class="img-fluid d-block mx-auto" src="{{ STATIC_URL }}img/logos/img-tools-4.png" alt="">
          </a>
        </div>
        <div class="col-md-3 col-sm-6">
          <a href="#">
            <img class="img-fluid d-block mx-auto" src="{{ STATIC_URL }}img/logos/img-tools-2.png" alt="">
          </a>
        </div>
        <div class="col-md-3 col-sm-6">
          <a href="#">
            <img class="img-fluid d-block mx-auto" src="{{ STATIC_URL }}img/logos/img-tools-3.png" alt="">
          </a>
        </div>
        <div class="col-md-3 col-sm-6">
          <a href="#">
            <img class="img-fluid d-block mx-auto" src="{{ STATIC_URL }}img/logos/img-tools-1.png" alt="">
          </a>
        </div>
      </div>
    </div>
  </section>

  <!-- Contact -->
  <section class="page-section" id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading text-uppercase">{{ _("Contact") }}</h2>
          <h3 class="section-subheading text-muted">{{user|get_company_email}}</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <form id="contactForm" name="sentMessage" novalidate="novalidate">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <input class="form-control" id="name" type="text" placeholder="{{ _('Contact') }}" required="required" data-validation-required-message="Please enter your name.">
                  <p class="help-block text-danger"></p>
                </div>
                <div class="form-group">
                  <input class="form-control" id="email" type="email" placeholder="{{ _('Email') }}" required="required" data-validation-required-message="Please enter your email address.">
                  <p class="help-block text-danger"></p>
                </div>
                <div class="form-group">
                  <input class="form-control" id="phone" type="tel" placeholder="{{ _('Phone') }}" required="required" data-validation-required-message="Please enter your phone number.">
                  <p class="help-block text-danger"></p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <textarea class="form-control" id="message" placeholder="{{ _('Message') }}" required="required" data-validation-required-message="Please enter a message."></textarea>
                  <p class="help-block text-danger"></p>
                </div>
              </div>
              <div class="clearfix"></div>
              <div class="col-lg-12 text-center">
                <div id="success"></div>
                <button id="sendMessageButton" class="btn btn-primary btn-xl text-uppercase" type="submit">{{ _("Send email") }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>

<!-- Footer -->
  <footer class="footer">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-4">
          <span class="copyright">Copyright &copy;  <a style="color:black;" href="http://www.pyerp.cl/"><b>PyERP</b></a> 2019</span>
        </div>
        <div class="col-md-4">
          <ul class="list-inline social-buttons">
            <li class="list-inline-item">
              <a href="https://{{ user|get_company_instagram }}">
                <i class="fab fa-instagram"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://{{ user|get_company_facebook }}">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://{{ user|get_company_linkedin }}">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </li>
          </ul>
        </div>
        <div class="col-md-4">
          <ul class="list-inline quicklinks">
            <li class="list-inline-item">
              <a style="color:black;" href="{% url 'home:home-license' %}">{{ _('License') }}</a>
            </li>
            <!--
            <li class="list-inline-item">
              <a style="color:black;" href="#">Términos de Uso</a>
            </li>
            -->
          </ul>
        </div>
      </div>
    </div>



  </footer>


  <!-- Bootstrap core JavaScript -->
  <script src="{{ STATIC_URL }}vendor/jquery/jquery.min.js"></script>
  <script src="{{ STATIC_URL }}vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="{{ STATIC_URL }}vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Contact form JavaScript -->
  <script src="{{ STATIC_URL }}js/jqBootstrapValidation.js"></script>
  <script src="{{ STATIC_URL }}js/contact_me.js"></script>

  <!-- Custom scripts for this template -->
  <script src="{{ STATIC_URL }}js/agency.min.js"></script>

  <script src="{{ STATIC_URL }}js/bootstrap-input-spinner.js"></script>
  <script>
      $("input[type='number']").inputSpinner()
  </script>

    {% if user|get_company_whatsapp %}
    <div class="chatbot" style="bottom:10px; left:10px; position: fixed; z-index: 99999999;">
       <div class="ccw_style9 animated no-animation ccw-no-hover-an">
          <a target="_blank" href="https://wa.me/{{user|get_company_whatsapp }}" class="img-icon-a nofocus">
             <img class="img-icon ccw-analytics" id="style-9" data-ccw="style-9" style="height: 48px;" src="{{ STATIC_URL }}/img/whatsapp-icon-square.svg" alt="WhatsApp chat"/>
           </a>
       </div>
	</div>
    {% endif %}

app/home/templates/home/head.html
{% load erp_tags %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    {% block meta %}{{ meta|safe }}{% endblock %}
    <title> {{ user|get_company_name }} | {% if user|get_company_slogan %} {{ user|get_company_slogan }} {% else %} By PyERP {% endif %} </title>
    <!-- Bootstrap core CSS -->
    <link href="{{ STATIC_URL }}/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="{{ STATIC_URL }}/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" href="{{ STATIC_URL }}./dist/favicon.png" type="image/x-icon"/>
    <!-- Custom styles for this template -->
    <link href="{{ STATIC_URL }}css/agency.css" rel="stylesheet">
    {% if user|web_under_construction %}
      <meta http-equiv="Refresh" content="0; url={% url 'home:under-construction' %}">
    {% endif %}

    {% block head %}
    {% endblock %}

</head>

  <style>
    body{
       color: {{ web_parameter.font_color }};
    }

    header.masthead {
      color: {{ web_parameter.font_color }};
      background-color: {{ web_parameter.main_color }};
    }

    a{
       color: {{ web_parameter.font_color }};
     }

    a:hover{
       color: {{ web_parameter.font_color_strong }};
     }

     .nav-link{
       color: {{ web_parameter.font_color }};
     }

     #mainNav.navbar-shrink {
     background-color: {{ web_parameter.main_color }};
        }

    section#contact,
    section#team,
    section#portfolio  {
        background-color: {{ web_parameter.main_color }};
    }

    .timeline > li .timeline-image {
  background-color: {{ web_parameter.main_color }};
    }

    section#services h2, section#services h4, section#about h2, section#about h4{
        color: {{ web_parameter.font_color_strong }};
     }

     section#portfolio .portfolio-caption{
        color: {{ web_parameter.font_color_strong }};
     }

     .text-primary {
        color: {{ web_parameter.main_color }} !important;
    }

    .strong_font, .page-section{
        color: {{ web_parameter.font_color_strong }};
    }

    .page-section a{
        color: {{ web_parameter.font_color }};
    }

    .list-group a{
        color: {{ web_parameter.font_color_strong }};
    }

    .btn-primary{
        background-color: {{ web_parameter.font_color_strong }} !important;
        border-color: {{ web_parameter.font_color_strong }} !important;
    }

    textarea {
        color: {{ web_parameter.font_color_strong }} !important;
    }

    footer {
        color: {{ web_parameter.font_color_strong }} !important;
    }

    .navbar-toggler-right
    {
        background-color: {{ web_parameter.font_color_strong }} !important;
        color: {{ web_parameter.font_color }} !important;
    }

    h5 a{
        color: {{ web_parameter.font_color_strong }} !important;
    }



  </style>

app/home/templates/home/home.html
{% load erp_tags %}
<!DOCTYPE html>
<html lang="en">
  {% include 'home/head.html' %}
  <body id="page-top">
  {{ web_parameter.parametro1 }}
    {% include 'home/nav_bar.html' %}
    <!-- Header -->
    <header class="masthead">
      <div class="container">
        <div class="intro-text" style="height:100px; padding-top:150px;">
          <div class="intro-heading text-uppercase">{{ header_title }}</div>
        </div>
      </div>
    </header>
    {% block content %}{% endblock %}
    {% include 'home/footer.html' %}
  </body>
</html>

app/home/templates/home/license.html
{% load static %}
{% load erp_tags %}
{% include "header.html" %}

  <!-- Header -->
   <header class="masthead" style="background-color: #6d4167">
    <div class="container">
      <div class="intro-text">
        <div class="intro-heading text-uppercase">The MIT License (MIT)</div>
        <div class="intro-lead-in">Copyright (c) 2019 PyERP Teamr</div>
      </div>
    </div>
  </header>

  <!-- Services -->
  <section class="page-section" id="services">
    <div class="container">

      <div class="row">
        <div class="col-lg-12">
          <p class="text-muted">
Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:</p>

          <p class="text-muted">
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.</p>

           <p class="text-muted">
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.</p>
        </div>
      </div>

    </div>
  </section>
{% include "footer.html" %}

app/home/templates/home/nav_bar.html
{% load erp_tags %}
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">
        <img src="{{ MEDIA_URL }}{{ user|get_company_logo }}" alt="PyERP"  height="80px">
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav text-uppercase ml-auto">
           <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'home:home-index' %}">{{ _("Home") }}</a>
          </li>

          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'home:home-index' %}#services">{{ _("Services") }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'home:home-index' %}#portfolio">{{ _("Portfolio") }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'home:home-index' %}#about">{{ _("About") }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'home:home-index' %}#team">{{ _("Team") }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'home:home-index' %}#contact">{{ _("Contact") }}</a>
          </li>

          {% if user|web_show_blog %}
           <li class="nav-item">
             <a class="nav-link js-scroll-trigger" href="{% url 'home:home-blog' %}">{{ _("Blog") }}</a>
           </li>
          {% endif %}

          {% if user|web_show_shop %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'home:web-shop' %}">{{ _("Shop") }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'home:web-shop' %}"><i class="fa fa-shopping-cart"></i>
              <b><sup class="cart_quantity" style="display: inline;">0</sup></b>
            </a>

          </li>
          {% endif %}

          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'home:login' %}">{{ _("Login") }}</a>
          </li>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>

app/home/templates/home/under_construction.html
{% load static %}
{% load erp_tags %}
<!doctype html>
{% if not user|web_under_construction %}
     <meta http-equiv="Refresh" content="0; url={% url 'base:home-index' %}">
{% endif %}

<title> {{ user|get_company_name }} | {{ user|get_company_slogan }} </title>
<style>
  body { text-align: center; padding: 150px; }
  h1 { font-size: 50px; }
  body { font: 20px Helvetica, sans-serif; color: #333; }
  article { display: block; text-align: left; width: 650px; margin: 0 auto; }
  a { color: #dc8100; text-decoration: none; }
  a:hover { color: #333; text-decoration: none; }
</style>

<article>
    <h1>Página en Construcción!</h1>
    <div>
        <p>Disculpe estamos en mantenimiento de nuestra Web si necesitas contactarnos lo puede hacer a <a href="mailto:hello@pyerp.cl">hello@pyerp.cl</a>, estaremos pronto de vuelta.</p>
        <p>&mdash; Equipo <b>PyERP</b></p>
    </div>
</article>